import type { NextPage } from 'next'
import Head from 'next/head'
import FifthSection from '../components/fifth-section'
import FirstSession from '../components/first-session'
import Footer from '../components/footer'
import FourthSession from '../components/fourth-session'
import SecondSession from '../components/second-session'
import ThirdSession from '../components/third-session'

const Home: NextPage = () => {
  return (
    <main>
      <Head>
        <title>FF Promotora</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" type="image/png" href="/favicon.png" />
      </Head>

      <FirstSession/>
      <SecondSession/>
      <ThirdSession/>
      <FourthSession/>
      <FifthSection/>
      <Footer/>
    </main>
  )
}

export default Home
